alias autoremove='sudo apt autoremove'
alias cp='cp -i'
alias df='df -h'
alias du='du -h'
alias gpt='tgpt -m'
alias grep='grep --color=auto'
alias ll='ls -l'
alias lla='ls -la'
alias ln='ln -i'
alias ls='ls --color=auto'
alias mv='mv -i'
alias poweroff='systemctl poweroff'
alias py='python3'
alias python='python'
alias reboot='systemctl reboot'
alias rm='rm -i'
alias update='sudo apt update && sudo apt upgrade'
alias vi='vim'
