alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ln='ln -i'
alias vi='vim'
alias ls='ls --color=auto'
alias ll='ls -l'
alias lla='ls -la'
alias grep='grep --color=auto'
alias py='python3'
alias python='python'
alias update='sudo apt update && sudo apt upgrade'
alias autoremove='sudo apt autoremove'
alias poweroff='systemctl poweroff'
alias reboot='systemctl reboot'
