set -g renumber-window on
set -g base-index 1
set -g mode-keys vi
set -s set-clipboard on

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -i -sel clipboard'
bind-key f find-window ""

bind c new-window -c "#{pane_current_path}"
