[window]
opacity = 0.5

[font]
normal = { family = "CaskaydiaCove NF", style = "Regular"  }
bold = { family = "CaskaydiaCove NF", style = "Bold"  }
italic = { family = "CaskaydiaCove NF", style = "Italic"  }
bold_italic = { family = "CaskaydiaCove NF", style = "Bold Italic"  }
size = 11

[cursor]
style = { shape = "UnderLine", blinking = "On" }

[mouse]
hide_when_typing = true
