[general]
import = [ "~/.config/alacritty/kanagawa-dragon.toml" ]

[window]
opacity = 1.0

[font]
normal = { family = "Terminess Nerd Font", style = "Regular"  }
bold = { family = "Terminess Nerd Font", style = "Bold"  }
italic = { family = "Terminess Nerd Font", style = "Italic"  }
bold_italic = { family = "Terminus Nerd Font", style = "Bold Italic"  }
size = 12

[cursor]
style = { shape = "Block", blinking = "On" }

[mouse]
hide_when_typing = true
